// Code generated by protoc-gen-gogo.
// source: dbtesterpb/config_client_machine.proto
// DO NOT EDIT!

package dbtesterpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ConfigClientMachineInitial represents common control options on client machine.
type ConfigClientMachineInitial struct {
	PathPrefix                              string `protobuf:"bytes,1,opt,name=PathPrefix,proto3" json:"PathPrefix,omitempty" yaml:"path_prefix"`
	LogPath                                 string `protobuf:"bytes,2,opt,name=LogPath,proto3" json:"LogPath,omitempty" yaml:"log_path"`
	ClientSystemMetricsPath                 string `protobuf:"bytes,3,opt,name=ClientSystemMetricsPath,proto3" json:"ClientSystemMetricsPath,omitempty" yaml:"client_system_metrics_path"`
	ClientSystemMetricsInterpolatedPath     string `protobuf:"bytes,4,opt,name=ClientSystemMetricsInterpolatedPath,proto3" json:"ClientSystemMetricsInterpolatedPath,omitempty" yaml:"client_system_metrics_interpolated_path"`
	ClientLatencyThroughputTimeseriesPath   string `protobuf:"bytes,5,opt,name=ClientLatencyThroughputTimeseriesPath,proto3" json:"ClientLatencyThroughputTimeseriesPath,omitempty" yaml:"client_latency_throughput_timeseries_path"`
	ClientLatencyDistributionAllPath        string `protobuf:"bytes,6,opt,name=ClientLatencyDistributionAllPath,proto3" json:"ClientLatencyDistributionAllPath,omitempty" yaml:"client_latency_distribution_all_path"`
	ClientLatencyDistributionPercentilePath string `protobuf:"bytes,7,opt,name=ClientLatencyDistributionPercentilePath,proto3" json:"ClientLatencyDistributionPercentilePath,omitempty" yaml:"client_latency_distribution_percentile_path"`
	ClientLatencyDistributionSummaryPath    string `protobuf:"bytes,8,opt,name=ClientLatencyDistributionSummaryPath,proto3" json:"ClientLatencyDistributionSummaryPath,omitempty" yaml:"client_latency_distribution_summary_path"`
	ClientLatencyByKeyNumberPath            string `protobuf:"bytes,9,opt,name=ClientLatencyByKeyNumberPath,proto3" json:"ClientLatencyByKeyNumberPath,omitempty" yaml:"client_latency_by_key_number_path"`
	ServerDiskSpaceUsageSummaryPath         string `protobuf:"bytes,10,opt,name=ServerDiskSpaceUsageSummaryPath,proto3" json:"ServerDiskSpaceUsageSummaryPath,omitempty" yaml:"server_disk_space_usage_summary_path"`
	GoogleCloudProjectName                  string `protobuf:"bytes,100,opt,name=GoogleCloudProjectName,proto3" json:"GoogleCloudProjectName,omitempty" yaml:"google_cloud_project_name"`
	GoogleCloudStorageKeyPath               string `protobuf:"bytes,101,opt,name=GoogleCloudStorageKeyPath,proto3" json:"GoogleCloudStorageKeyPath,omitempty" yaml:"google_cloud_storage_key_path"`
	GoogleCloudStorageKey                   string `protobuf:"bytes,102,opt,name=GoogleCloudStorageKey,proto3" json:"GoogleCloudStorageKey,omitempty"`
	GoogleCloudStorageBucketName            string `protobuf:"bytes,103,opt,name=GoogleCloudStorageBucketName,proto3" json:"GoogleCloudStorageBucketName,omitempty" yaml:"google_cloud_storage_bucket_name"`
	GoogleCloudStorageSubDirectory          string `protobuf:"bytes,104,opt,name=GoogleCloudStorageSubDirectory,proto3" json:"GoogleCloudStorageSubDirectory,omitempty" yaml:"google_cloud_storage_sub_directory"`
}

func (m *ConfigClientMachineInitial) Reset()         { *m = ConfigClientMachineInitial{} }
func (m *ConfigClientMachineInitial) String() string { return proto.CompactTextString(m) }
func (*ConfigClientMachineInitial) ProtoMessage()    {}
func (*ConfigClientMachineInitial) Descriptor() ([]byte, []int) {
	return fileDescriptorConfigClientMachine, []int{0}
}

// ConfigClientMachineBenchmarkOptions represents benchmark options.
type ConfigClientMachineBenchmarkOptions struct {
	Type                       string  `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty" yaml:"type"`
	RequestNumber              int64   `protobuf:"varint,2,opt,name=RequestNumber,proto3" json:"RequestNumber,omitempty" yaml:"request_number"`
	ConnectionNumber           int64   `protobuf:"varint,3,opt,name=ConnectionNumber,proto3" json:"ConnectionNumber,omitempty" yaml:"connection_number"`
	ClientNumber               int64   `protobuf:"varint,4,opt,name=ClientNumber,proto3" json:"ClientNumber,omitempty" yaml:"client_number"`
	ConnectionClientNumbers    []int64 `protobuf:"varint,5,rep,packed,name=ConnectionClientNumbers" json:"ConnectionClientNumbers,omitempty" yaml:"connection_client_numbers"`
	RateLimitRequestsPerSecond int64   `protobuf:"varint,6,opt,name=RateLimitRequestsPerSecond,proto3" json:"RateLimitRequestsPerSecond,omitempty" yaml:"rate_limit_requests_per_second"`
	SameKey                    bool    `protobuf:"varint,7,opt,name=SameKey,proto3" json:"SameKey,omitempty" yaml:"same_key"`
	KeySizeBytes               int64   `protobuf:"varint,8,opt,name=KeySizeBytes,proto3" json:"KeySizeBytes,omitempty" yaml:"key_size_bytes"`
	ValueSizeBytes             int64   `protobuf:"varint,9,opt,name=ValueSizeBytes,proto3" json:"ValueSizeBytes,omitempty" yaml:"value_size_bytes"`
	StaleRead                  bool    `protobuf:"varint,10,opt,name=StaleRead,proto3" json:"StaleRead,omitempty" yaml:"stale_read"`
}

func (m *ConfigClientMachineBenchmarkOptions) Reset()         { *m = ConfigClientMachineBenchmarkOptions{} }
func (m *ConfigClientMachineBenchmarkOptions) String() string { return proto.CompactTextString(m) }
func (*ConfigClientMachineBenchmarkOptions) ProtoMessage()    {}
func (*ConfigClientMachineBenchmarkOptions) Descriptor() ([]byte, []int) {
	return fileDescriptorConfigClientMachine, []int{1}
}

// ConfigClientMachineBenchmarkSteps represents benchmark steps.
type ConfigClientMachineBenchmarkSteps struct {
	Step1StartDatabase  bool `protobuf:"varint,1,opt,name=Step1StartDatabase,proto3" json:"Step1StartDatabase,omitempty" yaml:"step1_start_database"`
	Step2StressDatabase bool `protobuf:"varint,2,opt,name=Step2StressDatabase,proto3" json:"Step2StressDatabase,omitempty" yaml:"step2_stress_database"`
	Step3StopDatabase   bool `protobuf:"varint,3,opt,name=Step3StopDatabase,proto3" json:"Step3StopDatabase,omitempty" yaml:"step3_stop_database"`
	Step4UploadLogs     bool `protobuf:"varint,4,opt,name=Step4UploadLogs,proto3" json:"Step4UploadLogs,omitempty" yaml:"step4_upload_logs"`
}

func (m *ConfigClientMachineBenchmarkSteps) Reset()         { *m = ConfigClientMachineBenchmarkSteps{} }
func (m *ConfigClientMachineBenchmarkSteps) String() string { return proto.CompactTextString(m) }
func (*ConfigClientMachineBenchmarkSteps) ProtoMessage()    {}
func (*ConfigClientMachineBenchmarkSteps) Descriptor() ([]byte, []int) {
	return fileDescriptorConfigClientMachine, []int{2}
}

// ConfigClientMachineAgentControl represents control options on client machine.
type ConfigClientMachineAgentControl struct {
	DatabaseID                          string                               `protobuf:"bytes,1,opt,name=DatabaseID,proto3" json:"DatabaseID,omitempty" yaml:"database_id"`
	DatabaseDescription                 string                               `protobuf:"bytes,2,opt,name=DatabaseDescription,proto3" json:"DatabaseDescription,omitempty" yaml:"database_description"`
	DatabaseTag                         string                               `protobuf:"bytes,3,opt,name=DatabaseTag,proto3" json:"DatabaseTag,omitempty" yaml:"database_tag"`
	PeerIPs                             []string                             `protobuf:"bytes,4,rep,name=PeerIPs" json:"PeerIPs,omitempty" yaml:"peer_ips"`
	PeerIPsString                       string                               `protobuf:"bytes,5,opt,name=PeerIPsString,proto3" json:"PeerIPsString,omitempty" yaml:"peer_ips_string"`
	AgentPortToConnect                  int64                                `protobuf:"varint,6,opt,name=AgentPortToConnect,proto3" json:"AgentPortToConnect,omitempty" yaml:"agent_port_to_connect"`
	AgentEndpoints                      []string                             `protobuf:"bytes,7,rep,name=AgentEndpoints" json:"AgentEndpoints,omitempty" yaml:"agent_endpoints"`
	DatabasePortToConnect               int64                                `protobuf:"varint,8,opt,name=DatabasePortToConnect,proto3" json:"DatabasePortToConnect,omitempty" yaml:"database_port_to_connect"`
	DatabaseEndpoints                   []string                             `protobuf:"bytes,9,rep,name=DatabaseEndpoints" json:"DatabaseEndpoints,omitempty" yaml:"database_endpoints"`
	Flag_Etcd_V2_3                      *Flag_Etcd_V2_3                      `protobuf:"bytes,100,opt,name=flag__etcd__v2_3,json=flagEtcdV23" json:"flag__etcd__v2_3,omitempty" yaml:"etcd__v2_3"`
	Flag_Etcd_V3_1                      *Flag_Etcd_V3_1                      `protobuf:"bytes,101,opt,name=flag__etcd__v3_1,json=flagEtcdV31" json:"flag__etcd__v3_1,omitempty" yaml:"etcd__v3_1"`
	Flag_Etcd_V3_2                      *Flag_Etcd_V3_2                      `protobuf:"bytes,102,opt,name=flag__etcd__v3_2,json=flagEtcdV32" json:"flag__etcd__v3_2,omitempty" yaml:"etcd__v3_2"`
	Flag_Etcd_Tip                       *Flag_Etcd_Tip                       `protobuf:"bytes,103,opt,name=flag__etcd__tip,json=flagEtcdTip" json:"flag__etcd__tip,omitempty" yaml:"etcd__tip"`
	Flag_Zookeeper_R3_4_9               *Flag_Zookeeper_R3_4_9               `protobuf:"bytes,200,opt,name=flag__zookeeper__r3_4_9,json=flagZookeeperR349" json:"flag__zookeeper__r3_4_9,omitempty" yaml:"zookeeper__r3_4_9"`
	Flag_Zookeeper_R3_5_2Alpha          *Flag_Zookeeper_R3_5_2Alpha          `protobuf:"bytes,201,opt,name=flag__zookeeper__r3_5_2_alpha,json=flagZookeeperR352Alpha" json:"flag__zookeeper__r3_5_2_alpha,omitempty" yaml:"zookeeper__r3_5_2_alpha"`
	Flag_Consul_V0_7_5                  *Flag_Consul_V0_7_5                  `protobuf:"bytes,300,opt,name=flag__consul__v0_7_5,json=flagConsulV075" json:"flag__consul__v0_7_5,omitempty" yaml:"consul__v0_7_5"`
	Flag_Consul_V0_8_0                  *Flag_Consul_V0_8_0                  `protobuf:"bytes,301,opt,name=flag__consul__v0_8_0,json=flagConsulV080" json:"flag__consul__v0_8_0,omitempty" yaml:"consul__v0_8_0"`
	Flag_Cetcd_Beta                     *Flag_Cetcd_Beta                     `protobuf:"bytes,400,opt,name=flag__cetcd__beta,json=flagCetcdBeta" json:"flag__cetcd__beta,omitempty" yaml:"cetcd__beta"`
	Flag_Zetcd_Beta                     *Flag_Zetcd_Beta                     `protobuf:"bytes,500,opt,name=flag__zetcd__beta,json=flagZetcdBeta" json:"flag__zetcd__beta,omitempty" yaml:"zetcd__beta"`
	ConfigClientMachineBenchmarkOptions *ConfigClientMachineBenchmarkOptions `protobuf:"bytes,1000,opt,name=ConfigClientMachineBenchmarkOptions" json:"ConfigClientMachineBenchmarkOptions,omitempty" yaml:"benchmark_options"`
	ConfigClientMachineBenchmarkSteps   *ConfigClientMachineBenchmarkSteps   `protobuf:"bytes,1001,opt,name=ConfigClientMachineBenchmarkSteps" json:"ConfigClientMachineBenchmarkSteps,omitempty" yaml:"benchmark_steps"`
}

func (m *ConfigClientMachineAgentControl) Reset()         { *m = ConfigClientMachineAgentControl{} }
func (m *ConfigClientMachineAgentControl) String() string { return proto.CompactTextString(m) }
func (*ConfigClientMachineAgentControl) ProtoMessage()    {}
func (*ConfigClientMachineAgentControl) Descriptor() ([]byte, []int) {
	return fileDescriptorConfigClientMachine, []int{3}
}

func init() {
	proto.RegisterType((*ConfigClientMachineInitial)(nil), "dbtesterpb.ConfigClientMachineInitial")
	proto.RegisterType((*ConfigClientMachineBenchmarkOptions)(nil), "dbtesterpb.ConfigClientMachineBenchmarkOptions")
	proto.RegisterType((*ConfigClientMachineBenchmarkSteps)(nil), "dbtesterpb.ConfigClientMachineBenchmarkSteps")
	proto.RegisterType((*ConfigClientMachineAgentControl)(nil), "dbtesterpb.ConfigClientMachineAgentControl")
}
func (m *ConfigClientMachineInitial) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigClientMachineInitial) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PathPrefix) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.PathPrefix)))
		i += copy(dAtA[i:], m.PathPrefix)
	}
	if len(m.LogPath) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.LogPath)))
		i += copy(dAtA[i:], m.LogPath)
	}
	if len(m.ClientSystemMetricsPath) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientSystemMetricsPath)))
		i += copy(dAtA[i:], m.ClientSystemMetricsPath)
	}
	if len(m.ClientSystemMetricsInterpolatedPath) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientSystemMetricsInterpolatedPath)))
		i += copy(dAtA[i:], m.ClientSystemMetricsInterpolatedPath)
	}
	if len(m.ClientLatencyThroughputTimeseriesPath) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientLatencyThroughputTimeseriesPath)))
		i += copy(dAtA[i:], m.ClientLatencyThroughputTimeseriesPath)
	}
	if len(m.ClientLatencyDistributionAllPath) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientLatencyDistributionAllPath)))
		i += copy(dAtA[i:], m.ClientLatencyDistributionAllPath)
	}
	if len(m.ClientLatencyDistributionPercentilePath) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientLatencyDistributionPercentilePath)))
		i += copy(dAtA[i:], m.ClientLatencyDistributionPercentilePath)
	}
	if len(m.ClientLatencyDistributionSummaryPath) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientLatencyDistributionSummaryPath)))
		i += copy(dAtA[i:], m.ClientLatencyDistributionSummaryPath)
	}
	if len(m.ClientLatencyByKeyNumberPath) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ClientLatencyByKeyNumberPath)))
		i += copy(dAtA[i:], m.ClientLatencyByKeyNumberPath)
	}
	if len(m.ServerDiskSpaceUsageSummaryPath) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.ServerDiskSpaceUsageSummaryPath)))
		i += copy(dAtA[i:], m.ServerDiskSpaceUsageSummaryPath)
	}
	if len(m.GoogleCloudProjectName) > 0 {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.GoogleCloudProjectName)))
		i += copy(dAtA[i:], m.GoogleCloudProjectName)
	}
	if len(m.GoogleCloudStorageKeyPath) > 0 {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.GoogleCloudStorageKeyPath)))
		i += copy(dAtA[i:], m.GoogleCloudStorageKeyPath)
	}
	if len(m.GoogleCloudStorageKey) > 0 {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.GoogleCloudStorageKey)))
		i += copy(dAtA[i:], m.GoogleCloudStorageKey)
	}
	if len(m.GoogleCloudStorageBucketName) > 0 {
		dAtA[i] = 0xba
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.GoogleCloudStorageBucketName)))
		i += copy(dAtA[i:], m.GoogleCloudStorageBucketName)
	}
	if len(m.GoogleCloudStorageSubDirectory) > 0 {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.GoogleCloudStorageSubDirectory)))
		i += copy(dAtA[i:], m.GoogleCloudStorageSubDirectory)
	}
	return i, nil
}

func (m *ConfigClientMachineBenchmarkOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigClientMachineBenchmarkOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Type) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if m.RequestNumber != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.RequestNumber))
	}
	if m.ConnectionNumber != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.ConnectionNumber))
	}
	if m.ClientNumber != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.ClientNumber))
	}
	if len(m.ConnectionClientNumbers) > 0 {
		dAtA2 := make([]byte, len(m.ConnectionClientNumbers)*10)
		var j1 int
		for _, num1 := range m.ConnectionClientNumbers {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x2a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if m.RateLimitRequestsPerSecond != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.RateLimitRequestsPerSecond))
	}
	if m.SameKey {
		dAtA[i] = 0x38
		i++
		if m.SameKey {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.KeySizeBytes != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.KeySizeBytes))
	}
	if m.ValueSizeBytes != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.ValueSizeBytes))
	}
	if m.StaleRead {
		dAtA[i] = 0x50
		i++
		if m.StaleRead {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *ConfigClientMachineBenchmarkSteps) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigClientMachineBenchmarkSteps) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Step1StartDatabase {
		dAtA[i] = 0x8
		i++
		if m.Step1StartDatabase {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Step2StressDatabase {
		dAtA[i] = 0x10
		i++
		if m.Step2StressDatabase {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Step3StopDatabase {
		dAtA[i] = 0x18
		i++
		if m.Step3StopDatabase {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Step4UploadLogs {
		dAtA[i] = 0x20
		i++
		if m.Step4UploadLogs {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *ConfigClientMachineAgentControl) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigClientMachineAgentControl) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.DatabaseID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.DatabaseID)))
		i += copy(dAtA[i:], m.DatabaseID)
	}
	if len(m.DatabaseDescription) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.DatabaseDescription)))
		i += copy(dAtA[i:], m.DatabaseDescription)
	}
	if len(m.DatabaseTag) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.DatabaseTag)))
		i += copy(dAtA[i:], m.DatabaseTag)
	}
	if len(m.PeerIPs) > 0 {
		for _, s := range m.PeerIPs {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.PeerIPsString) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(len(m.PeerIPsString)))
		i += copy(dAtA[i:], m.PeerIPsString)
	}
	if m.AgentPortToConnect != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.AgentPortToConnect))
	}
	if len(m.AgentEndpoints) > 0 {
		for _, s := range m.AgentEndpoints {
			dAtA[i] = 0x3a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.DatabasePortToConnect != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.DatabasePortToConnect))
	}
	if len(m.DatabaseEndpoints) > 0 {
		for _, s := range m.DatabaseEndpoints {
			dAtA[i] = 0x4a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.Flag_Etcd_V2_3 != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Etcd_V2_3.Size()))
		n3, err := m.Flag_Etcd_V2_3.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Flag_Etcd_V3_1 != nil {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Etcd_V3_1.Size()))
		n4, err := m.Flag_Etcd_V3_1.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.Flag_Etcd_V3_2 != nil {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Etcd_V3_2.Size()))
		n5, err := m.Flag_Etcd_V3_2.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.Flag_Etcd_Tip != nil {
		dAtA[i] = 0xba
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Etcd_Tip.Size()))
		n6, err := m.Flag_Etcd_Tip.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.Flag_Zookeeper_R3_4_9 != nil {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0xc
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Zookeeper_R3_4_9.Size()))
		n7, err := m.Flag_Zookeeper_R3_4_9.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if m.Flag_Zookeeper_R3_5_2Alpha != nil {
		dAtA[i] = 0xca
		i++
		dAtA[i] = 0xc
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Zookeeper_R3_5_2Alpha.Size()))
		n8, err := m.Flag_Zookeeper_R3_5_2Alpha.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.Flag_Consul_V0_7_5 != nil {
		dAtA[i] = 0xe2
		i++
		dAtA[i] = 0x12
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Consul_V0_7_5.Size()))
		n9, err := m.Flag_Consul_V0_7_5.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if m.Flag_Consul_V0_8_0 != nil {
		dAtA[i] = 0xea
		i++
		dAtA[i] = 0x12
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Consul_V0_8_0.Size()))
		n10, err := m.Flag_Consul_V0_8_0.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.Flag_Cetcd_Beta != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x19
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Cetcd_Beta.Size()))
		n11, err := m.Flag_Cetcd_Beta.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if m.Flag_Zetcd_Beta != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x1f
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.Flag_Zetcd_Beta.Size()))
		n12, err := m.Flag_Zetcd_Beta.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	if m.ConfigClientMachineBenchmarkOptions != nil {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.ConfigClientMachineBenchmarkOptions.Size()))
		n13, err := m.ConfigClientMachineBenchmarkOptions.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	if m.ConfigClientMachineBenchmarkSteps != nil {
		dAtA[i] = 0xca
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintConfigClientMachine(dAtA, i, uint64(m.ConfigClientMachineBenchmarkSteps.Size()))
		n14, err := m.ConfigClientMachineBenchmarkSteps.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	return i, nil
}

func encodeFixed64ConfigClientMachine(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32ConfigClientMachine(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintConfigClientMachine(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ConfigClientMachineInitial) Size() (n int) {
	var l int
	_ = l
	l = len(m.PathPrefix)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.LogPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientSystemMetricsPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientSystemMetricsInterpolatedPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientLatencyThroughputTimeseriesPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientLatencyDistributionAllPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientLatencyDistributionPercentilePath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientLatencyDistributionSummaryPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ClientLatencyByKeyNumberPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.ServerDiskSpaceUsageSummaryPath)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.GoogleCloudProjectName)
	if l > 0 {
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.GoogleCloudStorageKeyPath)
	if l > 0 {
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.GoogleCloudStorageKey)
	if l > 0 {
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.GoogleCloudStorageBucketName)
	if l > 0 {
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.GoogleCloudStorageSubDirectory)
	if l > 0 {
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	return n
}

func (m *ConfigClientMachineBenchmarkOptions) Size() (n int) {
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	if m.RequestNumber != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.RequestNumber))
	}
	if m.ConnectionNumber != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.ConnectionNumber))
	}
	if m.ClientNumber != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.ClientNumber))
	}
	if len(m.ConnectionClientNumbers) > 0 {
		l = 0
		for _, e := range m.ConnectionClientNumbers {
			l += sovConfigClientMachine(uint64(e))
		}
		n += 1 + sovConfigClientMachine(uint64(l)) + l
	}
	if m.RateLimitRequestsPerSecond != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.RateLimitRequestsPerSecond))
	}
	if m.SameKey {
		n += 2
	}
	if m.KeySizeBytes != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.KeySizeBytes))
	}
	if m.ValueSizeBytes != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.ValueSizeBytes))
	}
	if m.StaleRead {
		n += 2
	}
	return n
}

func (m *ConfigClientMachineBenchmarkSteps) Size() (n int) {
	var l int
	_ = l
	if m.Step1StartDatabase {
		n += 2
	}
	if m.Step2StressDatabase {
		n += 2
	}
	if m.Step3StopDatabase {
		n += 2
	}
	if m.Step4UploadLogs {
		n += 2
	}
	return n
}

func (m *ConfigClientMachineAgentControl) Size() (n int) {
	var l int
	_ = l
	l = len(m.DatabaseID)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.DatabaseDescription)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	l = len(m.DatabaseTag)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	if len(m.PeerIPs) > 0 {
		for _, s := range m.PeerIPs {
			l = len(s)
			n += 1 + l + sovConfigClientMachine(uint64(l))
		}
	}
	l = len(m.PeerIPsString)
	if l > 0 {
		n += 1 + l + sovConfigClientMachine(uint64(l))
	}
	if m.AgentPortToConnect != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.AgentPortToConnect))
	}
	if len(m.AgentEndpoints) > 0 {
		for _, s := range m.AgentEndpoints {
			l = len(s)
			n += 1 + l + sovConfigClientMachine(uint64(l))
		}
	}
	if m.DatabasePortToConnect != 0 {
		n += 1 + sovConfigClientMachine(uint64(m.DatabasePortToConnect))
	}
	if len(m.DatabaseEndpoints) > 0 {
		for _, s := range m.DatabaseEndpoints {
			l = len(s)
			n += 1 + l + sovConfigClientMachine(uint64(l))
		}
	}
	if m.Flag_Etcd_V2_3 != nil {
		l = m.Flag_Etcd_V2_3.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Etcd_V3_1 != nil {
		l = m.Flag_Etcd_V3_1.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Etcd_V3_2 != nil {
		l = m.Flag_Etcd_V3_2.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Etcd_Tip != nil {
		l = m.Flag_Etcd_Tip.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Zookeeper_R3_4_9 != nil {
		l = m.Flag_Zookeeper_R3_4_9.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Zookeeper_R3_5_2Alpha != nil {
		l = m.Flag_Zookeeper_R3_5_2Alpha.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Consul_V0_7_5 != nil {
		l = m.Flag_Consul_V0_7_5.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Consul_V0_8_0 != nil {
		l = m.Flag_Consul_V0_8_0.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Cetcd_Beta != nil {
		l = m.Flag_Cetcd_Beta.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.Flag_Zetcd_Beta != nil {
		l = m.Flag_Zetcd_Beta.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.ConfigClientMachineBenchmarkOptions != nil {
		l = m.ConfigClientMachineBenchmarkOptions.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	if m.ConfigClientMachineBenchmarkSteps != nil {
		l = m.ConfigClientMachineBenchmarkSteps.Size()
		n += 2 + l + sovConfigClientMachine(uint64(l))
	}
	return n
}

func sovConfigClientMachine(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozConfigClientMachine(x uint64) (n int) {
	return sovConfigClientMachine(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConfigClientMachineInitial) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfigClientMachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigClientMachineInitial: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigClientMachineInitial: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PathPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PathPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LogPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSystemMetricsPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientSystemMetricsPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSystemMetricsInterpolatedPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientSystemMetricsInterpolatedPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientLatencyThroughputTimeseriesPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientLatencyThroughputTimeseriesPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientLatencyDistributionAllPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientLatencyDistributionAllPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientLatencyDistributionPercentilePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientLatencyDistributionPercentilePath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientLatencyDistributionSummaryPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientLatencyDistributionSummaryPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientLatencyByKeyNumberPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientLatencyByKeyNumberPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerDiskSpaceUsageSummaryPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerDiskSpaceUsageSummaryPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 100:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudProjectName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudProjectName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 101:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageKeyPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageKeyPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 102:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 103:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageBucketName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageBucketName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 104:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageSubDirectory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageSubDirectory = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfigClientMachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigClientMachineBenchmarkOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfigClientMachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigClientMachineBenchmarkOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigClientMachineBenchmarkOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestNumber", wireType)
			}
			m.RequestNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestNumber |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionNumber", wireType)
			}
			m.ConnectionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectionNumber |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientNumber", wireType)
			}
			m.ClientNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientNumber |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowConfigClientMachine
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ConnectionClientNumbers = append(m.ConnectionClientNumbers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowConfigClientMachine
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthConfigClientMachine
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowConfigClientMachine
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ConnectionClientNumbers = append(m.ConnectionClientNumbers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionClientNumbers", wireType)
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimitRequestsPerSecond", wireType)
			}
			m.RateLimitRequestsPerSecond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateLimitRequestsPerSecond |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SameKey", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SameKey = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeySizeBytes", wireType)
			}
			m.KeySizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeySizeBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueSizeBytes", wireType)
			}
			m.ValueSizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValueSizeBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StaleRead", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StaleRead = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipConfigClientMachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigClientMachineBenchmarkSteps) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfigClientMachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigClientMachineBenchmarkSteps: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigClientMachineBenchmarkSteps: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Step1StartDatabase", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Step1StartDatabase = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Step2StressDatabase", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Step2StressDatabase = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Step3StopDatabase", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Step3StopDatabase = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Step4UploadLogs", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Step4UploadLogs = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipConfigClientMachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigClientMachineAgentControl) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfigClientMachine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigClientMachineAgentControl: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigClientMachineAgentControl: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseTag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseTag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerIPs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerIPs = append(m.PeerIPs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerIPsString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerIPsString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentPortToConnect", wireType)
			}
			m.AgentPortToConnect = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentPortToConnect |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentEndpoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentEndpoints = append(m.AgentEndpoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabasePortToConnect", wireType)
			}
			m.DatabasePortToConnect = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DatabasePortToConnect |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseEndpoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseEndpoints = append(m.DatabaseEndpoints, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 100:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Etcd_V2_3", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Etcd_V2_3 == nil {
				m.Flag_Etcd_V2_3 = &Flag_Etcd_V2_3{}
			}
			if err := m.Flag_Etcd_V2_3.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 101:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Etcd_V3_1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Etcd_V3_1 == nil {
				m.Flag_Etcd_V3_1 = &Flag_Etcd_V3_1{}
			}
			if err := m.Flag_Etcd_V3_1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 102:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Etcd_V3_2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Etcd_V3_2 == nil {
				m.Flag_Etcd_V3_2 = &Flag_Etcd_V3_2{}
			}
			if err := m.Flag_Etcd_V3_2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 103:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Etcd_Tip", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Etcd_Tip == nil {
				m.Flag_Etcd_Tip = &Flag_Etcd_Tip{}
			}
			if err := m.Flag_Etcd_Tip.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 200:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Zookeeper_R3_4_9", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Zookeeper_R3_4_9 == nil {
				m.Flag_Zookeeper_R3_4_9 = &Flag_Zookeeper_R3_4_9{}
			}
			if err := m.Flag_Zookeeper_R3_4_9.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 201:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Zookeeper_R3_5_2Alpha", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Zookeeper_R3_5_2Alpha == nil {
				m.Flag_Zookeeper_R3_5_2Alpha = &Flag_Zookeeper_R3_5_2Alpha{}
			}
			if err := m.Flag_Zookeeper_R3_5_2Alpha.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 300:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Consul_V0_7_5", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Consul_V0_7_5 == nil {
				m.Flag_Consul_V0_7_5 = &Flag_Consul_V0_7_5{}
			}
			if err := m.Flag_Consul_V0_7_5.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 301:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Consul_V0_8_0", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Consul_V0_8_0 == nil {
				m.Flag_Consul_V0_8_0 = &Flag_Consul_V0_8_0{}
			}
			if err := m.Flag_Consul_V0_8_0.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 400:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Cetcd_Beta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Cetcd_Beta == nil {
				m.Flag_Cetcd_Beta = &Flag_Cetcd_Beta{}
			}
			if err := m.Flag_Cetcd_Beta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 500:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flag_Zetcd_Beta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Flag_Zetcd_Beta == nil {
				m.Flag_Zetcd_Beta = &Flag_Zetcd_Beta{}
			}
			if err := m.Flag_Zetcd_Beta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1000:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigClientMachineBenchmarkOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConfigClientMachineBenchmarkOptions == nil {
				m.ConfigClientMachineBenchmarkOptions = &ConfigClientMachineBenchmarkOptions{}
			}
			if err := m.ConfigClientMachineBenchmarkOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1001:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigClientMachineBenchmarkSteps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConfigClientMachineBenchmarkSteps == nil {
				m.ConfigClientMachineBenchmarkSteps = &ConfigClientMachineBenchmarkSteps{}
			}
			if err := m.ConfigClientMachineBenchmarkSteps.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfigClientMachine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfigClientMachine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfigClientMachine(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfigClientMachine
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfigClientMachine
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthConfigClientMachine
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowConfigClientMachine
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipConfigClientMachine(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthConfigClientMachine = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfigClientMachine   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("dbtesterpb/config_client_machine.proto", fileDescriptorConfigClientMachine)
}

var fileDescriptorConfigClientMachine = []byte{
	// 1761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0x6d, 0x6f, 0x1b, 0x49,
	0x1d, 0x3f, 0xd7, 0xed, 0x35, 0x99, 0xb4, 0x4d, 0x33, 0x7d, 0x88, 0x9b, 0xa6, 0x99, 0xdc, 0xa6,
	0xe5, 0x5a, 0x1d, 0xcd, 0x83, 0x9d, 0xde, 0xb5, 0x08, 0x04, 0x75, 0x72, 0x40, 0x95, 0xdc, 0x9d,
	0x59, 0xe7, 0x8a, 0xa8, 0x10, 0xc3, 0x78, 0x3d, 0x59, 0xef, 0x65, 0xbd, 0xb3, 0xec, 0x8c, 0x23,
	0x1c, 0xde, 0x22, 0x21, 0x21, 0x21, 0xdd, 0xcb, 0x7b, 0xc9, 0x07, 0x80, 0xaf, 0x81, 0xca, 0x3b,
	0x3e, 0xc1, 0x0a, 0x7a, 0x42, 0x82, 0xb7, 0x2b, 0x3e, 0x00, 0x9a, 0xff, 0xae, 0xed, 0x59, 0x7b,
	0xe3, 0xf8, 0x9d, 0x77, 0xfe, 0xbf, 0xa7, 0x99, 0x9d, 0xa7, 0x35, 0xfa, 0x4e, 0xbb, 0xa5, 0xb8,
	0x54, 0x3c, 0x0a, 0x5b, 0x5b, 0x8e, 0x08, 0x8e, 0x3d, 0x97, 0x3a, 0xbe, 0xc7, 0x03, 0x45, 0xbb,
	0xcc, 0xe9, 0x78, 0x01, 0xdf, 0x0c, 0x23, 0xa1, 0x04, 0x46, 0x23, 0xdc, 0xca, 0x53, 0xd7, 0x53,
	0x9d, 0x5e, 0x6b, 0xd3, 0x11, 0xdd, 0x2d, 0x57, 0xb8, 0x62, 0x0b, 0x20, 0xad, 0xde, 0x31, 0x3c,
	0xc1, 0x03, 0xfc, 0x4a, 0xa9, 0x2b, 0x2b, 0x86, 0xc5, 0xb1, 0xcf, 0x5c, 0xca, 0x95, 0xd3, 0xce,
	0x6a, 0x64, 0xbc, 0x76, 0x26, 0xc4, 0x09, 0xe7, 0x21, 0x8f, 0x32, 0xc0, 0xea, 0x38, 0xc0, 0x11,
	0x81, 0xec, 0xf9, 0x59, 0xf5, 0xfe, 0x04, 0xdd, 0xd0, 0x9e, 0x28, 0x3a, 0xa3, 0xa2, 0xf5, 0xed,
	0x35, 0xb4, 0xb2, 0x07, 0xfd, 0xdd, 0x83, 0xee, 0x7e, 0x96, 0xf6, 0xf6, 0x55, 0xe0, 0x29, 0x8f,
	0xf9, 0xf8, 0x63, 0x84, 0x1a, 0x4c, 0x75, 0x1a, 0x11, 0x3f, 0xf6, 0x7e, 0x5b, 0x29, 0xad, 0x97,
	0x1e, 0xcf, 0xd7, 0xef, 0x26, 0x31, 0xc1, 0x7d, 0xd6, 0xf5, 0xbf, 0x67, 0x85, 0x4c, 0x75, 0x68,
	0x08, 0x45, 0xcb, 0x36, 0x90, 0xf8, 0x29, 0xba, 0x7a, 0x28, 0x5c, 0xdd, 0x50, 0xb9, 0x04, 0xa4,
	0x5b, 0x49, 0x4c, 0x16, 0x53, 0x92, 0x2f, 0x5c, 0xaa, 0x89, 0x96, 0x3d, 0xc0, 0x60, 0x8a, 0x96,
	0x53, 0xfb, 0x66, 0x5f, 0x2a, 0xde, 0xfd, 0x8c, 0xab, 0xc8, 0x73, 0x24, 0xd0, 0xcb, 0x40, 0x7f,
	0x94, 0xc4, 0xe4, 0x83, 0x94, 0x9e, 0xbd, 0x16, 0x09, 0x48, 0xda, 0x4d, 0xa1, 0x99, 0xe0, 0x79,
	0x2a, 0xf8, 0xf7, 0x25, 0xb4, 0x51, 0x50, 0x7b, 0x15, 0xe8, 0x61, 0x11, 0x3e, 0x53, 0xbc, 0x0d,
	0x6e, 0x97, 0xc1, 0xad, 0x9a, 0xc4, 0x64, 0x73, 0x9a, 0x9b, 0x67, 0xf0, 0x32, 0xeb, 0x59, 0xe4,
	0xf1, 0x1f, 0x4b, 0xe8, 0x51, 0x8a, 0x3b, 0x64, 0x8a, 0x07, 0x4e, 0xff, 0xa8, 0x13, 0x89, 0x9e,
	0xdb, 0x09, 0x7b, 0xea, 0xc8, 0xeb, 0x72, 0xc9, 0x23, 0x8f, 0xa7, 0xdd, 0xbe, 0x02, 0x41, 0x76,
	0x93, 0x98, 0x6c, 0xe7, 0x82, 0xf8, 0x29, 0x8f, 0xaa, 0x21, 0x91, 0xaa, 0x21, 0x33, 0x8b, 0x32,
	0x9b, 0x05, 0xfe, 0x1d, 0x5a, 0xcf, 0x01, 0xf7, 0x3d, 0xa9, 0x22, 0xaf, 0xd5, 0x53, 0x9e, 0x08,
	0x5e, 0xfa, 0x3e, 0xc4, 0x78, 0x1f, 0x62, 0x6c, 0x25, 0x31, 0xf9, 0xa8, 0x30, 0x46, 0xdb, 0xe0,
	0x50, 0xe6, 0xfb, 0x59, 0x82, 0x0b, 0x85, 0xf1, 0xd7, 0x25, 0xf4, 0xe1, 0xb9, 0xa0, 0x06, 0x8f,
	0x1c, 0x1e, 0x28, 0xcf, 0xe7, 0x10, 0xe2, 0x2a, 0x84, 0xf8, 0x38, 0x89, 0x49, 0xf5, 0xe2, 0x10,
	0xe1, 0x90, 0x9b, 0x65, 0x99, 0xd5, 0x06, 0xff, 0xa1, 0x84, 0x1e, 0x9e, 0x8b, 0x6d, 0xf6, 0xba,
	0x5d, 0x16, 0xf5, 0x21, 0xcf, 0x1c, 0xe4, 0xa9, 0x25, 0x31, 0xd9, 0xba, 0x38, 0x8f, 0x4c, 0x89,
	0x59, 0x98, 0x99, 0x0c, 0x70, 0x88, 0x56, 0x73, 0xb8, 0x7a, 0xff, 0x80, 0xf7, 0x3f, 0xef, 0x75,
	0x5b, 0x3c, 0x82, 0x00, 0xf3, 0x10, 0xe0, 0xbb, 0x49, 0x4c, 0x1e, 0x17, 0x06, 0x68, 0xf5, 0xe9,
	0x09, 0xef, 0xd3, 0x00, 0x18, 0x99, 0xf3, 0x54, 0x45, 0xdc, 0x47, 0xa4, 0xc9, 0xa3, 0x53, 0x1e,
	0xed, 0x7b, 0xf2, 0xa4, 0x19, 0x32, 0x87, 0x7f, 0x29, 0x99, 0xcb, 0xcd, 0x5e, 0xa3, 0xf1, 0xa9,
	0x20, 0x81, 0xa0, 0x7b, 0x7b, 0x42, 0xa5, 0xa6, 0xd0, 0x9e, 0xe6, 0x8c, 0xf5, 0xf8, 0x22, 0x5d,
	0xfc, 0x4b, 0x74, 0xf7, 0x27, 0x42, 0xb8, 0x3e, 0xdf, 0xf3, 0x45, 0xaf, 0xdd, 0x88, 0xc4, 0x57,
	0xdc, 0x51, 0x9f, 0xb3, 0x2e, 0xaf, 0xb4, 0xc1, 0xf1, 0x61, 0x12, 0x93, 0xf5, 0xd4, 0xd1, 0x05,
	0x1c, 0x75, 0x34, 0x90, 0x86, 0x29, 0x92, 0x06, 0xac, 0xcb, 0x2d, 0xfb, 0x1c, 0x0d, 0x7c, 0x8c,
	0xee, 0x19, 0x95, 0xa6, 0x12, 0x11, 0x73, 0xf9, 0x01, 0x4f, 0xbb, 0xc4, 0xc1, 0xe0, 0x71, 0x12,
	0x93, 0x87, 0x05, 0x06, 0x32, 0x05, 0xc3, 0x50, 0xa6, 0x7d, 0x39, 0x5f, 0x0a, 0xef, 0xa2, 0x3b,
	0x85, 0xc5, 0xca, 0xb1, 0xf6, 0xb0, 0x8b, 0x8b, 0x58, 0xa0, 0xd5, 0xc9, 0x42, 0xbd, 0xe7, 0x9c,
	0xf0, 0x74, 0x04, 0x5c, 0x08, 0xf8, 0x51, 0x12, 0x93, 0x0f, 0xa7, 0x04, 0x6c, 0x01, 0x21, 0x1b,
	0x88, 0xa9, 0x82, 0xb8, 0x87, 0xd6, 0x26, 0xeb, 0xcd, 0x5e, 0x6b, 0xdf, 0x8b, 0xb8, 0xa3, 0x44,
	0xd4, 0xaf, 0x74, 0xc0, 0xf2, 0x69, 0x12, 0x93, 0x27, 0x53, 0x2c, 0x65, 0xaf, 0x45, 0xdb, 0x03,
	0x8e, 0x65, 0x5f, 0x20, 0x6a, 0xfd, 0xed, 0x0a, 0xda, 0x28, 0x38, 0x65, 0xea, 0x3c, 0x70, 0x3a,
	0x5d, 0x16, 0x9d, 0x7c, 0x11, 0xea, 0x25, 0x20, 0xf1, 0x06, 0xba, 0x7c, 0xd4, 0x0f, 0x79, 0x76,
	0xd0, 0x2c, 0x26, 0x31, 0x59, 0x48, 0x43, 0xa8, 0x7e, 0xc8, 0x2d, 0x1b, 0x8a, 0xf8, 0x87, 0xe8,
	0xba, 0xcd, 0x7f, 0xd3, 0xe3, 0x52, 0xa5, 0x13, 0x18, 0x4e, 0x98, 0x72, 0xfd, 0x5e, 0x12, 0x93,
	0x3b, 0x29, 0x3a, 0x4a, 0xcb, 0xd9, 0x02, 0xb0, 0xec, 0x3c, 0x1e, 0xff, 0x14, 0xdd, 0xdc, 0x13,
	0x41, 0xc0, 0x1d, 0x6d, 0x9a, 0x69, 0x94, 0x41, 0x63, 0x35, 0x89, 0x49, 0x25, 0x5b, 0x52, 0x43,
	0xc4, 0x50, 0x66, 0x82, 0x85, 0xbf, 0x8f, 0xae, 0xa5, 0x1d, 0xca, 0x54, 0x2e, 0x83, 0x4a, 0x25,
	0x89, 0xc9, 0xed, 0xdc, 0xc2, 0x1c, 0x28, 0xe4, 0xd0, 0xf8, 0x57, 0x68, 0x79, 0xa4, 0x68, 0x56,
	0x64, 0xe5, 0xca, 0x7a, 0xf9, 0x71, 0xd9, 0x9c, 0xfa, 0x46, 0x9c, 0x9c, 0xa6, 0xd4, 0x87, 0x5e,
	0xb1, 0x08, 0xf6, 0xd0, 0x8a, 0xcd, 0x14, 0x3f, 0xf4, 0xba, 0x9e, 0xca, 0x46, 0x40, 0x36, 0x78,
	0xd4, 0xe4, 0x8e, 0x08, 0xda, 0xb0, 0xb5, 0x97, 0xeb, 0x4f, 0x92, 0x98, 0x3c, 0xca, 0x46, 0x8d,
	0x29, 0x4e, 0x7d, 0x0d, 0xa6, 0xd9, 0x00, 0x4a, 0xbd, 0x9b, 0x52, 0x09, 0x78, 0xcb, 0x9e, 0x22,
	0xa6, 0xcf, 0xfb, 0x26, 0xeb, 0xc2, 0x84, 0xd7, 0xbb, 0xf5, 0x9c, 0x79, 0xde, 0x4b, 0xd6, 0x85,
	0x45, 0x64, 0xd9, 0x03, 0x0c, 0xfe, 0x01, 0xba, 0x76, 0xc0, 0xfb, 0x4d, 0xef, 0x8c, 0xd7, 0xfb,
	0x8a, 0x4b, 0xd8, 0x51, 0x73, 0x6f, 0x50, 0xaf, 0x39, 0xe9, 0x9d, 0x71, 0xda, 0xd2, 0x75, 0xcb,
	0xce, 0xc1, 0xf1, 0x1e, 0xba, 0xf1, 0x9a, 0xf9, 0x3d, 0x3e, 0x12, 0x98, 0x07, 0x81, 0xfb, 0x49,
	0x4c, 0x96, 0x53, 0x81, 0x53, 0x5d, 0xcf, 0x49, 0x8c, 0x51, 0x70, 0x0d, 0xcd, 0x37, 0x15, 0xf3,
	0xb9, 0xcd, 0x59, 0x1b, 0x36, 0xb7, 0xb9, 0xfa, 0x9d, 0x24, 0x26, 0x4b, 0x59, 0x68, 0x5d, 0xa2,
	0x11, 0x67, 0x6d, 0xcb, 0x1e, 0xe1, 0xac, 0xf8, 0x12, 0xfa, 0x60, 0xda, 0x44, 0x6e, 0x2a, 0x1e,
	0x4a, 0xfc, 0x05, 0xc2, 0xfa, 0xc7, 0x4e, 0x53, 0xb1, 0x48, 0xed, 0x33, 0xc5, 0x5a, 0x4c, 0xa6,
	0x93, 0x7a, 0xae, 0x4e, 0x92, 0x98, 0xdc, 0x1f, 0x78, 0xf0, 0x70, 0x87, 0x4a, 0x0d, 0xa2, 0xed,
	0x0c, 0x65, 0xd9, 0x05, 0x54, 0x6c, 0xa3, 0x5b, 0xba, 0xb5, 0xda, 0x54, 0x11, 0x97, 0x72, 0xa8,
	0x78, 0x09, 0x14, 0xd7, 0x93, 0x98, 0xac, 0x8e, 0x14, 0xab, 0x54, 0x02, 0xca, 0x90, 0x2c, 0x22,
	0xe3, 0x43, 0xb4, 0xa4, 0x9b, 0x6b, 0x4d, 0x25, 0xc2, 0xa1, 0x62, 0x19, 0x14, 0xd7, 0x92, 0x98,
	0xac, 0x8c, 0x14, 0x6b, 0x7a, 0xd9, 0x87, 0x86, 0xde, 0x24, 0x11, 0xff, 0x18, 0x2d, 0xea, 0xc6,
	0xdd, 0x2f, 0x43, 0x5f, 0xb0, 0xf6, 0xa1, 0x70, 0x25, 0x2c, 0x86, 0x39, 0x73, 0x49, 0x69, 0xad,
	0x5d, 0xda, 0x03, 0x04, 0xf5, 0x85, 0x2b, 0x2d, 0x7b, 0x9c, 0x64, 0xfd, 0x7b, 0x11, 0x91, 0x82,
	0x01, 0x7e, 0xe9, 0xf2, 0x40, 0xed, 0x89, 0x40, 0x45, 0x02, 0x2e, 0xa5, 0x03, 0xdf, 0x57, 0xfb,
	0x93, 0x97, 0xd2, 0x41, 0x4e, 0xea, 0xb5, 0x2d, 0xdb, 0x40, 0xe2, 0x9f, 0xa1, 0x5b, 0x83, 0xa7,
	0x7d, 0x2e, 0x9d, 0xc8, 0x83, 0x5d, 0x27, 0xbb, 0xa0, 0x1a, 0xef, 0x65, 0x28, 0xd0, 0x1e, 0xa1,
	0x2c, 0xbb, 0x88, 0x8b, 0x5f, 0xa0, 0x85, 0x41, 0xf3, 0x11, 0x73, 0xb3, 0xcb, 0xea, 0x72, 0x12,
	0x93, 0x5b, 0x63, 0x52, 0x8a, 0xb9, 0x96, 0x6d, 0x62, 0xf5, 0x92, 0x69, 0x70, 0x1e, 0xbd, 0x6a,
	0xe8, 0x91, 0x2a, 0xe7, 0xaf, 0xc8, 0x21, 0xe7, 0x11, 0xf5, 0x42, 0x69, 0xd9, 0x03, 0x0c, 0xfe,
	0x11, 0xba, 0x9e, 0xfd, 0x6c, 0xaa, 0xc8, 0x0b, 0xdc, 0xec, 0x86, 0xb8, 0x92, 0xc4, 0xe4, 0x6e,
	0x9e, 0xa4, 0xdf, 0xbf, 0x17, 0xb8, 0x96, 0x9d, 0x27, 0xe0, 0x06, 0xc2, 0x30, 0x8c, 0x0d, 0x11,
	0xa9, 0x23, 0x91, 0x6d, 0x1a, 0xd9, 0x36, 0x60, 0xcc, 0x21, 0xa6, 0x31, 0x34, 0x14, 0x91, 0xa2,
	0x4a, 0xd0, 0x6c, 0xdf, 0xb1, 0xec, 0x02, 0x2e, 0xae, 0xa3, 0x1b, 0xd0, 0xfa, 0x69, 0xd0, 0x0e,
	0x85, 0x17, 0x28, 0x59, 0xb9, 0x0a, 0x3d, 0x31, 0x42, 0xa5, 0x6a, 0x7c, 0x00, 0xb0, 0xec, 0x31,
	0x06, 0xfe, 0x05, 0xba, 0x33, 0x18, 0x95, 0x7c, 0xb0, 0x74, 0x4f, 0xd8, 0x48, 0x62, 0x42, 0xc6,
	0xc6, 0x72, 0x22, 0x5b, 0xb1, 0x02, 0x3e, 0x40, 0x4b, 0x83, 0xc2, 0x28, 0xe1, 0x3c, 0x24, 0x7c,
	0x90, 0xc4, 0xe4, 0xde, 0x98, 0xac, 0x11, 0x72, 0x92, 0x87, 0xdf, 0xa0, 0x9b, 0xf0, 0xf1, 0x04,
	0x5f, 0x6d, 0x94, 0x9e, 0x56, 0x69, 0x0d, 0x2e, 0x28, 0x0b, 0xd5, 0xd5, 0xcd, 0xd1, 0x07, 0xd6,
	0xe6, 0x38, 0xc6, 0xdc, 0x53, 0x46, 0xad, 0x96, 0xbd, 0xa0, 0x81, 0x9f, 0x2a, 0xa7, 0xfd, 0xba,
	0x5a, 0x9b, 0xd0, 0xae, 0xd1, 0x1d, 0xb8, 0x9b, 0x4c, 0xd3, 0xae, 0xd1, 0x9d, 0x02, 0xed, 0x1a,
	0xdd, 0x31, 0xb5, 0x6b, 0x3b, 0x05, 0xda, 0x55, 0xb8, 0x93, 0x4c, 0xd7, 0xae, 0x16, 0x6a, 0x57,
	0x73, 0xda, 0x55, 0xfc, 0x73, 0xb4, 0x68, 0xf2, 0x94, 0x17, 0xc2, 0x8d, 0x65, 0xa1, 0x7a, 0xff,
	0x3c, 0x69, 0xe5, 0x85, 0xf5, 0xdb, 0x49, 0x4c, 0x6e, 0x9a, 0xca, 0xca, 0x0b, 0x0d, 0xe1, 0x23,
	0x2f, 0xc4, 0xa7, 0x68, 0x39, 0x65, 0x0d, 0x3f, 0x83, 0x29, 0x8d, 0x6a, 0x74, 0x97, 0xbe, 0xa8,
	0xbc, 0x2d, 0x81, 0xc3, 0xc6, 0xa4, 0xc3, 0x04, 0xd6, 0xdc, 0x7b, 0x26, 0x8a, 0x96, 0xbd, 0xa4,
	0x69, 0x6f, 0x06, 0xed, 0x76, 0x6d, 0xf7, 0x05, 0xfe, 0x53, 0x09, 0x3d, 0x28, 0x12, 0x7b, 0x46,
	0xab, 0x94, 0xf9, 0x61, 0x87, 0x55, 0xfe, 0x9e, 0xda, 0x3f, 0xb9, 0xc8, 0x7e, 0xc8, 0xa8, 0x5b,
	0x49, 0x4c, 0xd6, 0x8a, 0x42, 0x0c, 0x21, 0x96, 0x7d, 0x77, 0x2c, 0xca, 0xb3, 0xea, 0x4b, 0x5d,
	0xc0, 0x5f, 0xa1, 0xdb, 0xa9, 0x78, 0xfa, 0xb5, 0x4f, 0xe9, 0xe9, 0x36, 0xfd, 0x84, 0x3e, 0xab,
	0xfc, 0xe5, 0x12, 0xa4, 0x58, 0x9f, 0x4c, 0x91, 0x07, 0x9a, 0x47, 0x6a, 0xbe, 0x62, 0xd9, 0x37,
	0x34, 0x61, 0x0f, 0x1a, 0x5f, 0x6f, 0x7f, 0xf2, 0xac, 0xd0, 0xeb, 0x39, 0xdd, 0xae, 0xfc, 0x75,
	0x16, 0xaf, 0xe7, 0x74, 0xfb, 0x1c, 0xaf, 0xe7, 0x74, 0x7b, 0xcc, 0xeb, 0xf9, 0x36, 0xfe, 0x35,
	0x5a, 0xca, 0x24, 0xd2, 0x19, 0xd0, 0xe2, 0x8a, 0x55, 0xbe, 0x2e, 0x83, 0xd1, 0x83, 0x02, 0xa3,
	0x11, 0xca, 0xdc, 0xe8, 0x8d, 0x66, 0xcb, 0xbe, 0x0e, 0x16, 0xba, 0xa5, 0xce, 0x15, 0x1b, 0x39,
	0x9c, 0x19, 0x0e, 0xff, 0x3b, 0xd7, 0xe1, 0xac, 0xd8, 0xe1, 0x6c, 0xc2, 0xe1, 0xcd, 0xd0, 0xe1,
	0xcf, 0xa5, 0x99, 0xee, 0xb4, 0x95, 0xff, 0x5c, 0x05, 0xd3, 0x2d, 0xd3, 0x74, 0x06, 0x9e, 0x39,
	0x79, 0x5b, 0x83, 0x1a, 0x15, 0x69, 0xd1, 0xb2, 0x67, 0xba, 0x4e, 0x7f, 0x53, 0x9a, 0xe1, 0xb6,
	0x52, 0xf9, 0x6f, 0x1a, 0xf0, 0xe9, 0xac, 0x01, 0x81, 0x65, 0xee, 0xf1, 0xa3, 0x78, 0xfa, 0x84,
	0x97, 0x96, 0x7d, 0xb1, 0x69, 0xfd, 0xf6, 0xdb, 0x7f, 0xad, 0xbd, 0xf7, 0xf6, 0xdd, 0x5a, 0xe9,
	0x1f, 0xef, 0xd6, 0x4a, 0xff, 0x7c, 0xb7, 0x56, 0xfa, 0xe6, 0xdb, 0xb5, 0xf7, 0x5a, 0xef, 0xc3,
	0x9f, 0x52, 0xb5, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x09, 0x69, 0xa2, 0x8e, 0x13, 0x00,
	0x00,
}
