// Code generated by protoc-gen-gogo.
// source: dbtesterpb/message.proto
// DO NOT EDIT!

/*
	Package dbtesterpb is a generated protocol buffer package.

	It is generated from these files:
		dbtesterpb/message.proto

	It has these top-level messages:
		Request
		Response
*/
package dbtesterpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Operation int32

const (
	Request_Start     Request_Operation = 0
	Request_Stop      Request_Operation = 1
	Request_Heartbeat Request_Operation = 2
)

var Request_Operation_name = map[int32]string{
	0: "Start",
	1: "Stop",
	2: "Heartbeat",
}
var Request_Operation_value = map[string]int32{
	"Start":     0,
	"Stop":      1,
	"Heartbeat": 2,
}

func (x Request_Operation) String() string {
	return proto.EnumName(Request_Operation_name, int32(x))
}
func (Request_Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 0} }

type Request_Database int32

const (
	Request_etcdv2    Request_Database = 0
	Request_etcdv3    Request_Database = 1
	Request_zookeeper Request_Database = 2
	Request_consul    Request_Database = 3
	Request_zetcd     Request_Database = 4
	Request_cetcd     Request_Database = 5
)

var Request_Database_name = map[int32]string{
	0: "etcdv2",
	1: "etcdv3",
	2: "zookeeper",
	3: "consul",
	4: "zetcd",
	5: "cetcd",
}
var Request_Database_value = map[string]int32{
	"etcdv2":    0,
	"etcdv3":    1,
	"zookeeper": 2,
	"consul":    3,
	"zetcd":     4,
	"cetcd":     5,
}

func (x Request_Database) String() string {
	return proto.EnumName(Request_Database_name, int32(x))
}
func (Request_Database) EnumDescriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 1} }

type Request struct {
	Operation           Request_Operation  `protobuf:"varint,1,opt,name=operation,proto3,enum=dbtesterpb.Request_Operation" json:"operation,omitempty"`
	TriggerLogUpload    bool               `protobuf:"varint,2,opt,name=triggerLogUpload,proto3" json:"triggerLogUpload,omitempty"`
	DatabaseID          Request_Database   `protobuf:"varint,3,opt,name=databaseID,proto3,enum=dbtesterpb.Request_Database" json:"databaseID,omitempty"`
	DatabaseTag         string             `protobuf:"bytes,4,opt,name=databaseTag,proto3" json:"databaseTag,omitempty"`
	PeerIPsString       string             `protobuf:"bytes,5,opt,name=peerIPsString,proto3" json:"peerIPsString,omitempty"`
	IpIndex             uint32             `protobuf:"varint,6,opt,name=ipIndex,proto3" json:"ipIndex,omitempty"`
	CurrentClientNumber int64              `protobuf:"varint,7,opt,name=currentClientNumber,proto3" json:"currentClientNumber,omitempty"`
	Control             *Request_Control   `protobuf:"bytes,8,opt,name=control" json:"control,omitempty"`
	Etcdv3Config        *Request_Etcdv3    `protobuf:"bytes,9,opt,name=etcdv3Config" json:"etcdv3Config,omitempty"`
	ZookeeperConfig     *Request_Zookeeper `protobuf:"bytes,10,opt,name=zookeeperConfig" json:"zookeeperConfig,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

type Request_Control struct {
	GoogleCloudProjectName         string `protobuf:"bytes,1,opt,name=googleCloudProjectName,proto3" json:"googleCloudProjectName,omitempty"`
	GoogleCloudStorageKey          string `protobuf:"bytes,2,opt,name=googleCloudStorageKey,proto3" json:"googleCloudStorageKey,omitempty"`
	GoogleCloudStorageBucketName   string `protobuf:"bytes,3,opt,name=googleCloudStorageBucketName,proto3" json:"googleCloudStorageBucketName,omitempty"`
	GoogleCloudStorageSubDirectory string `protobuf:"bytes,4,opt,name=googleCloudStorageSubDirectory,proto3" json:"googleCloudStorageSubDirectory,omitempty"`
}

func (m *Request_Control) Reset()                    { *m = Request_Control{} }
func (m *Request_Control) String() string            { return proto.CompactTextString(m) }
func (*Request_Control) ProtoMessage()               {}
func (*Request_Control) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 0} }

type Request_Etcdv3 struct {
	SnapCount      int64 `protobuf:"varint,1,opt,name=snapCount,proto3" json:"snapCount,omitempty"`
	QuotaSizeBytes int64 `protobuf:"varint,2,opt,name=quotaSizeBytes,proto3" json:"quotaSizeBytes,omitempty"`
}

func (m *Request_Etcdv3) Reset()                    { *m = Request_Etcdv3{} }
func (m *Request_Etcdv3) String() string            { return proto.CompactTextString(m) }
func (*Request_Etcdv3) ProtoMessage()               {}
func (*Request_Etcdv3) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 1} }

type Request_Zookeeper struct {
	MyID                 uint32 `protobuf:"varint,1,opt,name=myID,proto3" json:"myID,omitempty"`
	TickTime             int64  `protobuf:"varint,2,opt,name=tickTime,proto3" json:"tickTime,omitempty"`
	ClientPort           int64  `protobuf:"varint,3,opt,name=clientPort,proto3" json:"clientPort,omitempty"`
	InitLimit            int64  `protobuf:"varint,4,opt,name=initLimit,proto3" json:"initLimit,omitempty"`
	SyncLimit            int64  `protobuf:"varint,5,opt,name=syncLimit,proto3" json:"syncLimit,omitempty"`
	SnapCount            int64  `protobuf:"varint,6,opt,name=snapCount,proto3" json:"snapCount,omitempty"`
	MaxClientConnections int64  `protobuf:"varint,7,opt,name=maxClientConnections,proto3" json:"maxClientConnections,omitempty"`
}

func (m *Request_Zookeeper) Reset()                    { *m = Request_Zookeeper{} }
func (m *Request_Zookeeper) String() string            { return proto.CompactTextString(m) }
func (*Request_Zookeeper) ProtoMessage()               {}
func (*Request_Zookeeper) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 2} }

type Response struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// DatasizeOnDisk is the data size of the database on disk.
	// It measures after database is requested to stop.
	DatasizeOnDisk int64 `protobuf:"varint,2,opt,name=datasizeOnDisk,proto3" json:"datasizeOnDisk,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "dbtesterpb.Request")
	proto.RegisterType((*Request_Control)(nil), "dbtesterpb.Request.Control")
	proto.RegisterType((*Request_Etcdv3)(nil), "dbtesterpb.Request.Etcdv3")
	proto.RegisterType((*Request_Zookeeper)(nil), "dbtesterpb.Request.Zookeeper")
	proto.RegisterType((*Response)(nil), "dbtesterpb.Response")
	proto.RegisterEnum("dbtesterpb.Request_Operation", Request_Operation_name, Request_Operation_value)
	proto.RegisterEnum("dbtesterpb.Request_Database", Request_Database_name, Request_Database_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Transporter service

type TransporterClient interface {
	Transfer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type transporterClient struct {
	cc *grpc.ClientConn
}

func NewTransporterClient(cc *grpc.ClientConn) TransporterClient {
	return &transporterClient{cc}
}

func (c *transporterClient) Transfer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/dbtesterpb.Transporter/Transfer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Transporter service

type TransporterServer interface {
	Transfer(context.Context, *Request) (*Response, error)
}

func RegisterTransporterServer(s *grpc.Server, srv TransporterServer) {
	s.RegisterService(&_Transporter_serviceDesc, srv)
}

func _Transporter_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransporterServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbtesterpb.Transporter/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransporterServer).Transfer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbtesterpb.Transporter",
	HandlerType: (*TransporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _Transporter_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbtesterpb/message.proto",
}

func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Operation != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Operation))
	}
	if m.TriggerLogUpload {
		dAtA[i] = 0x10
		i++
		if m.TriggerLogUpload {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.DatabaseID != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.DatabaseID))
	}
	if len(m.DatabaseTag) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.DatabaseTag)))
		i += copy(dAtA[i:], m.DatabaseTag)
	}
	if len(m.PeerIPsString) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.PeerIPsString)))
		i += copy(dAtA[i:], m.PeerIPsString)
	}
	if m.IpIndex != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.IpIndex))
	}
	if m.CurrentClientNumber != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.CurrentClientNumber))
	}
	if m.Control != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Control.Size()))
		n1, err := m.Control.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Etcdv3Config != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Etcdv3Config.Size()))
		n2, err := m.Etcdv3Config.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.ZookeeperConfig != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.ZookeeperConfig.Size()))
		n3, err := m.ZookeeperConfig.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *Request_Control) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request_Control) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.GoogleCloudProjectName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.GoogleCloudProjectName)))
		i += copy(dAtA[i:], m.GoogleCloudProjectName)
	}
	if len(m.GoogleCloudStorageKey) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.GoogleCloudStorageKey)))
		i += copy(dAtA[i:], m.GoogleCloudStorageKey)
	}
	if len(m.GoogleCloudStorageBucketName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.GoogleCloudStorageBucketName)))
		i += copy(dAtA[i:], m.GoogleCloudStorageBucketName)
	}
	if len(m.GoogleCloudStorageSubDirectory) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.GoogleCloudStorageSubDirectory)))
		i += copy(dAtA[i:], m.GoogleCloudStorageSubDirectory)
	}
	return i, nil
}

func (m *Request_Etcdv3) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request_Etcdv3) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SnapCount != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.SnapCount))
	}
	if m.QuotaSizeBytes != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.QuotaSizeBytes))
	}
	return i, nil
}

func (m *Request_Zookeeper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request_Zookeeper) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MyID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.MyID))
	}
	if m.TickTime != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.TickTime))
	}
	if m.ClientPort != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.ClientPort))
	}
	if m.InitLimit != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.InitLimit))
	}
	if m.SyncLimit != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.SyncLimit))
	}
	if m.SnapCount != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.SnapCount))
	}
	if m.MaxClientConnections != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.MaxClientConnections))
	}
	return i, nil
}

func (m *Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Success {
		dAtA[i] = 0x8
		i++
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.DatasizeOnDisk != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.DatasizeOnDisk))
	}
	return i, nil
}

func encodeFixed64Message(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Message(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Request) Size() (n int) {
	var l int
	_ = l
	if m.Operation != 0 {
		n += 1 + sovMessage(uint64(m.Operation))
	}
	if m.TriggerLogUpload {
		n += 2
	}
	if m.DatabaseID != 0 {
		n += 1 + sovMessage(uint64(m.DatabaseID))
	}
	l = len(m.DatabaseTag)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.PeerIPsString)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.IpIndex != 0 {
		n += 1 + sovMessage(uint64(m.IpIndex))
	}
	if m.CurrentClientNumber != 0 {
		n += 1 + sovMessage(uint64(m.CurrentClientNumber))
	}
	if m.Control != nil {
		l = m.Control.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Etcdv3Config != nil {
		l = m.Etcdv3Config.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ZookeeperConfig != nil {
		l = m.ZookeeperConfig.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *Request_Control) Size() (n int) {
	var l int
	_ = l
	l = len(m.GoogleCloudProjectName)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudStorageKey)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudStorageBucketName)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudStorageSubDirectory)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *Request_Etcdv3) Size() (n int) {
	var l int
	_ = l
	if m.SnapCount != 0 {
		n += 1 + sovMessage(uint64(m.SnapCount))
	}
	if m.QuotaSizeBytes != 0 {
		n += 1 + sovMessage(uint64(m.QuotaSizeBytes))
	}
	return n
}

func (m *Request_Zookeeper) Size() (n int) {
	var l int
	_ = l
	if m.MyID != 0 {
		n += 1 + sovMessage(uint64(m.MyID))
	}
	if m.TickTime != 0 {
		n += 1 + sovMessage(uint64(m.TickTime))
	}
	if m.ClientPort != 0 {
		n += 1 + sovMessage(uint64(m.ClientPort))
	}
	if m.InitLimit != 0 {
		n += 1 + sovMessage(uint64(m.InitLimit))
	}
	if m.SyncLimit != 0 {
		n += 1 + sovMessage(uint64(m.SyncLimit))
	}
	if m.SnapCount != 0 {
		n += 1 + sovMessage(uint64(m.SnapCount))
	}
	if m.MaxClientConnections != 0 {
		n += 1 + sovMessage(uint64(m.MaxClientConnections))
	}
	return n
}

func (m *Response) Size() (n int) {
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	if m.DatasizeOnDisk != 0 {
		n += 1 + sovMessage(uint64(m.DatasizeOnDisk))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			m.Operation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Operation |= (Request_Operation(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TriggerLogUpload", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TriggerLogUpload = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseID", wireType)
			}
			m.DatabaseID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DatabaseID |= (Request_Database(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseTag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseTag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerIPsString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerIPsString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpIndex", wireType)
			}
			m.IpIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IpIndex |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentClientNumber", wireType)
			}
			m.CurrentClientNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentClientNumber |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Control", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Control == nil {
				m.Control = &Request_Control{}
			}
			if err := m.Control.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Etcdv3Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Etcdv3Config == nil {
				m.Etcdv3Config = &Request_Etcdv3{}
			}
			if err := m.Etcdv3Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZookeeperConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ZookeeperConfig == nil {
				m.ZookeeperConfig = &Request_Zookeeper{}
			}
			if err := m.ZookeeperConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Request_Control) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Control: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Control: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudProjectName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudProjectName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageBucketName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageBucketName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageSubDirectory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageSubDirectory = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Request_Etcdv3) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Etcdv3: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Etcdv3: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapCount", wireType)
			}
			m.SnapCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapCount |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaSizeBytes", wireType)
			}
			m.QuotaSizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaSizeBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Request_Zookeeper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Zookeeper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Zookeeper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MyID", wireType)
			}
			m.MyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MyID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TickTime", wireType)
			}
			m.TickTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TickTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientPort", wireType)
			}
			m.ClientPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientPort |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitLimit", wireType)
			}
			m.InitLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitLimit |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncLimit", wireType)
			}
			m.SyncLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SyncLimit |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapCount", wireType)
			}
			m.SnapCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapCount |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClientConnections", wireType)
			}
			m.MaxClientConnections = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClientConnections |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatasizeOnDisk", wireType)
			}
			m.DatasizeOnDisk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DatasizeOnDisk |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessage(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("dbtesterpb/message.proto", fileDescriptorMessage) }

var fileDescriptorMessage = []byte{
	// 742 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0xeb, 0x44,
	0x10, 0x8f, 0xeb, 0x36, 0xb1, 0xa7, 0xf4, 0x61, 0xed, 0x2b, 0xc8, 0x0a, 0x25, 0x8a, 0x22, 0x84,
	0x22, 0x24, 0x52, 0x94, 0xf2, 0xe7, 0x00, 0xe2, 0xd0, 0x84, 0x07, 0x15, 0x55, 0x5f, 0xb5, 0x29,
	0x17, 0x6e, 0x6b, 0x67, 0x6a, 0x96, 0xc6, 0xbb, 0x7e, 0xbb, 0x6b, 0xf4, 0x92, 0x2b, 0x5f, 0x82,
	0x8f, 0xd4, 0x03, 0x07, 0x3e, 0x02, 0x94, 0x13, 0xdf, 0x02, 0x79, 0x6d, 0xe7, 0x4f, 0x6b, 0x78,
	0xb7, 0x99, 0xdf, 0xef, 0x37, 0xb3, 0x3b, 0xb3, 0x33, 0x0b, 0xe1, 0x3c, 0x32, 0xa8, 0x0d, 0xaa,
	0x2c, 0x3a, 0x4d, 0x51, 0x6b, 0x96, 0xe0, 0x28, 0x53, 0xd2, 0x48, 0x02, 0x1b, 0xa6, 0xfb, 0x71,
	0xc2, 0xcd, 0x4f, 0x79, 0x34, 0x8a, 0x65, 0x7a, 0x9a, 0xc8, 0x44, 0x9e, 0x5a, 0x49, 0x94, 0xdf,
	0x5a, 0xcf, 0x3a, 0xd6, 0x2a, 0x43, 0x07, 0xbf, 0xfb, 0xd0, 0xa1, 0xf8, 0x2a, 0x47, 0x6d, 0xc8,
	0x97, 0xe0, 0xcb, 0x0c, 0x15, 0x33, 0x5c, 0x8a, 0xd0, 0xe9, 0x3b, 0xc3, 0x67, 0xe3, 0xf7, 0x47,
	0x9b, 0xd4, 0xa3, 0x4a, 0x37, 0x7a, 0x59, 0x8b, 0xe8, 0x46, 0x4f, 0x3e, 0x82, 0xc0, 0x28, 0x9e,
	0x24, 0xa8, 0x2e, 0x65, 0xf2, 0x43, 0xb6, 0x90, 0x6c, 0x1e, 0xee, 0xf5, 0x9d, 0xa1, 0x47, 0x9f,
	0xe0, 0xe4, 0x2b, 0x80, 0x39, 0x33, 0x2c, 0x62, 0x1a, 0x2f, 0xa6, 0xa1, 0x6b, 0x4f, 0x3a, 0x69,
	0x3a, 0x69, 0x5a, 0xa9, 0xe8, 0x96, 0x9e, 0xf4, 0xe1, 0xb0, 0xf6, 0x6e, 0x58, 0x12, 0xee, 0xf7,
	0x9d, 0xa1, 0x4f, 0xb7, 0x21, 0xf2, 0x01, 0x1c, 0x65, 0x88, 0xea, 0xe2, 0x5a, 0xcf, 0x8c, 0xe2,
	0x22, 0x09, 0x0f, 0xac, 0x66, 0x17, 0x24, 0x21, 0x74, 0x78, 0x76, 0x21, 0xe6, 0xf8, 0x3a, 0x6c,
	0xf7, 0x9d, 0xe1, 0x11, 0xad, 0x5d, 0xf2, 0x09, 0x3c, 0x8f, 0x73, 0xa5, 0x50, 0x98, 0xc9, 0x82,
	0xa3, 0x30, 0x57, 0x79, 0x1a, 0xa1, 0x0a, 0x3b, 0x7d, 0x67, 0xe8, 0xd2, 0x26, 0x8a, 0x7c, 0x06,
	0x9d, 0x58, 0x0a, 0xa3, 0xe4, 0x22, 0xf4, 0xfa, 0xce, 0xf0, 0x70, 0xfc, 0x5e, 0x53, 0x39, 0x93,
	0x52, 0x42, 0x6b, 0x2d, 0xf9, 0x1a, 0xde, 0x42, 0x13, 0xcf, 0x7f, 0x39, 0x9b, 0x48, 0x71, 0xcb,
	0x93, 0xd0, 0xb7, 0xb1, 0xdd, 0xa6, 0xd8, 0x6f, 0xac, 0x8e, 0xee, 0xe8, 0xc9, 0xb7, 0xf0, 0xf6,
	0x4a, 0xca, 0x3b, 0xc4, 0x0c, 0x55, 0x95, 0x02, 0x6c, 0x8a, 0xc6, 0x77, 0xfb, 0xb1, 0x96, 0xd2,
	0xc7, 0x51, 0xdd, 0x5f, 0xf7, 0xa0, 0x53, 0xdd, 0x8e, 0x7c, 0x0e, 0xef, 0x26, 0x52, 0x26, 0x0b,
	0x9c, 0x2c, 0x64, 0x3e, 0xbf, 0x56, 0xf2, 0x67, 0x8c, 0xcd, 0x15, 0x4b, 0xd1, 0xce, 0x84, 0x4f,
	0xff, 0x83, 0x25, 0x9f, 0xc2, 0x3b, 0x5b, 0xcc, 0xcc, 0x48, 0xc5, 0x12, 0xfc, 0x1e, 0x97, 0x76,
	0x0c, 0x7c, 0xda, 0x4c, 0x92, 0x73, 0x38, 0x79, 0x4a, 0x9c, 0xe7, 0xf1, 0x1d, 0x96, 0x67, 0xba,
	0x36, 0xf8, 0x7f, 0x35, 0xe4, 0x05, 0xf4, 0x9e, 0xf2, 0xb3, 0x3c, 0x9a, 0x72, 0x85, 0xb1, 0x91,
	0x6a, 0x59, 0x0d, 0xc9, 0x1b, 0x54, 0xdd, 0x2b, 0x68, 0x97, 0x6d, 0x26, 0x27, 0xe0, 0x6b, 0xc1,
	0xb2, 0x89, 0xcc, 0x85, 0xb1, 0x65, 0xbb, 0x74, 0x03, 0x90, 0x0f, 0xe1, 0xd9, 0xab, 0x5c, 0x1a,
	0x36, 0xe3, 0x2b, 0x3c, 0x5f, 0x1a, 0xd4, 0xb6, 0x44, 0x97, 0x3e, 0x42, 0xbb, 0xff, 0x38, 0xe0,
	0xaf, 0x9b, 0x4e, 0x08, 0xec, 0xa7, 0xcb, 0x8b, 0xa9, 0x4d, 0x77, 0x44, 0xad, 0x4d, 0xba, 0xe0,
	0x19, 0x1e, 0xdf, 0xdd, 0xf0, 0x14, 0xab, 0x1c, 0x6b, 0x9f, 0xf4, 0x00, 0x62, 0x3b, 0x63, 0xd7,
	0x52, 0x19, 0xdb, 0x07, 0x97, 0x6e, 0x21, 0xc5, 0x1d, 0xb9, 0xe0, 0xe6, 0x92, 0xa7, 0xdc, 0xd8,
	0x02, 0x5d, 0xba, 0x01, 0x6c, 0x05, 0x4b, 0x11, 0x97, 0xec, 0x41, 0x55, 0x41, 0x0d, 0xec, 0xd6,
	0xd7, 0x7e, 0x5c, 0xdf, 0x18, 0x8e, 0x53, 0xf6, 0xba, 0x1c, 0xf0, 0x89, 0x14, 0x02, 0xe3, 0x62,
	0xc5, 0x75, 0xb5, 0x00, 0x8d, 0xdc, 0xe0, 0x14, 0xfc, 0xf5, 0xbf, 0x40, 0x7c, 0x38, 0x98, 0x19,
	0xa6, 0x4c, 0xd0, 0x22, 0x1e, 0xec, 0xcf, 0x8c, 0xcc, 0x02, 0x87, 0x1c, 0x81, 0xff, 0x1d, 0x32,
	0x65, 0x22, 0x64, 0x26, 0xd8, 0x1b, 0xcc, 0xc0, 0xab, 0xd7, 0x9b, 0x00, 0xb4, 0xed, 0x5c, 0x8f,
	0x83, 0xd6, 0xda, 0x3e, 0x2b, 0x43, 0xd6, 0x93, 0x1a, 0xec, 0x15, 0x54, 0x2c, 0x85, 0xce, 0x17,
	0x81, 0x5b, 0x1c, 0xb1, 0x2a, 0x74, 0xc1, 0x7e, 0x61, 0xc6, 0xd6, 0x3c, 0x18, 0x5c, 0x82, 0x47,
	0x51, 0x67, 0x52, 0x68, 0x2c, 0xf6, 0x5b, 0xe7, 0x71, 0x8c, 0x5a, 0xdb, 0x96, 0x7b, 0xb4, 0x76,
	0x8b, 0xf7, 0x2b, 0xbe, 0x0b, 0xcd, 0x57, 0xf8, 0x52, 0x4c, 0xb9, 0xbe, 0xab, 0xdf, 0x6f, 0x17,
	0x1d, 0xbf, 0x80, 0xc3, 0x1b, 0xc5, 0x84, 0xce, 0xa4, 0x32, 0xa8, 0xc8, 0x17, 0xe0, 0x59, 0xf7,
	0x16, 0x15, 0x79, 0xde, 0xb0, 0x60, 0xdd, 0xe3, 0x5d, 0xb0, 0xbc, 0xc7, 0xa0, 0x75, 0x7e, 0x7c,
	0xff, 0x57, 0xaf, 0x75, 0xff, 0xd0, 0x73, 0xfe, 0x78, 0xe8, 0x39, 0x7f, 0x3e, 0xf4, 0x9c, 0xdf,
	0xfe, 0xee, 0xb5, 0xa2, 0xb6, 0xfd, 0x81, 0xcf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x93, 0xb5,
	0x0d, 0x1a, 0xd8, 0x05, 0x00, 0x00,
}
