// Code generated by protoc-gen-gogo.
// source: message.proto
// DO NOT EDIT!

/*
	Package agent is a generated protocol buffer package.

	It is generated from these files:
		message.proto

	It has these top-level messages:
		Request
		Response
*/
package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Operation int32

const (
	Request_Start   Request_Operation = 0
	Request_Stop    Request_Operation = 1
	Request_Restart Request_Operation = 2
)

var Request_Operation_name = map[int32]string{
	0: "Start",
	1: "Stop",
	2: "Restart",
}
var Request_Operation_value = map[string]int32{
	"Start":   0,
	"Stop":    1,
	"Restart": 2,
}

func (x Request_Operation) String() string {
	return proto.EnumName(Request_Operation_name, int32(x))
}
func (Request_Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 0} }

type Request_Database int32

const (
	Request_etcdv3    Request_Database = 0
	Request_etcdv2    Request_Database = 1
	Request_ZooKeeper Request_Database = 2
	Request_Consul    Request_Database = 3
)

var Request_Database_name = map[int32]string{
	0: "etcdv3",
	1: "etcdv2",
	2: "ZooKeeper",
	3: "Consul",
}
var Request_Database_value = map[string]int32{
	"etcdv3":    0,
	"etcdv2":    1,
	"ZooKeeper": 2,
	"Consul":    3,
}

func (x Request_Database) String() string {
	return proto.EnumName(Request_Database_name, int32(x))
}
func (Request_Database) EnumDescriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0, 1} }

type Request struct {
	Operation    Request_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=agent.Request_Operation" json:"operation,omitempty"`
	Database     Request_Database  `protobuf:"varint,2,opt,name=database,proto3,enum=agent.Request_Database" json:"database,omitempty"`
	PeerIPString string            `protobuf:"bytes,3,opt,name=peerIPString,proto3" json:"peerIPString,omitempty"`
	// ServerIPIndex is the index in peerIPs that points to the
	// corresponding remote IP.
	ServerIndex uint32 `protobuf:"varint,4,opt,name=serverIndex,proto3" json:"serverIndex,omitempty"`
	// TestName prefixes all logs to be generated in agent.
	TestName string `protobuf:"bytes,5,opt,name=testName,proto3" json:"testName,omitempty"`
	// GoogleCloudProjectName is the project name to use
	// to upload logs.
	GoogleCloudProjectName string `protobuf:"bytes,6,opt,name=googleCloudProjectName,proto3" json:"googleCloudProjectName,omitempty"`
	// GoogleCloudStorageKey is the key to be used to upload
	// data and logs to Google Cloud Storage and others.
	GoogleCloudStorageKey string `protobuf:"bytes,7,opt,name=googleCloudStorageKey,proto3" json:"googleCloudStorageKey,omitempty"`
	// GoogleCloudStorageBucketName is the bucket name to store all data and logs.
	GoogleCloudStorageBucketName string `protobuf:"bytes,8,opt,name=googleCloudStorageBucketName,proto3" json:"googleCloudStorageBucketName,omitempty"`
	// GoogleCloudStorageSubDirectory is the sub-directory name to store data.
	GoogleCloudStorageSubDirectory string `protobuf:"bytes,9,opt,name=googleCloudStorageSubDirectory,proto3" json:"googleCloudStorageSubDirectory,omitempty"`
	// ZookeeperMyID is myid that needs to be stored as a file in the remote machine.
	ZookeeperMyID uint32 `protobuf:"varint,10,opt,name=zookeeperMyID,proto3" json:"zookeeperMyID,omitempty"`
	// ZookeeperMaxClientCnxns limits the number of concurrent connections
	// (at the socket level) that a single client, identified by IP address.
	ZookeeperMaxClientCnxns int64 `protobuf:"varint,11,opt,name=zookeeperMaxClientCnxns,proto3" json:"zookeeperMaxClientCnxns,omitempty"`
	// ZookeeperSnapCount is 100,000 by default.
	ZookeeperSnapCount int64 `protobuf:"varint,12,opt,name=zookeeperSnapCount,proto3" json:"zookeeperSnapCount,omitempty"`
	// EtcdCompression specifies etcd compression algorithm.
	EtcdCompression string `protobuf:"bytes,13,opt,name=etcdCompression,proto3" json:"etcdCompression,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

type Response struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "agent.Request")
	proto.RegisterType((*Response)(nil), "agent.Response")
	proto.RegisterEnum("agent.Request_Operation", Request_Operation_name, Request_Operation_value)
	proto.RegisterEnum("agent.Request_Database", Request_Database_name, Request_Database_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Transporter service

type TransporterClient interface {
	Transfer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type transporterClient struct {
	cc *grpc.ClientConn
}

func NewTransporterClient(cc *grpc.ClientConn) TransporterClient {
	return &transporterClient{cc}
}

func (c *transporterClient) Transfer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/agent.Transporter/Transfer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Transporter service

type TransporterServer interface {
	Transfer(context.Context, *Request) (*Response, error)
}

func RegisterTransporterServer(s *grpc.Server, srv TransporterServer) {
	s.RegisterService(&_Transporter_serviceDesc, srv)
}

func _Transporter_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransporterServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Transporter/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransporterServer).Transfer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Transporter",
	HandlerType: (*TransporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _Transporter_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptorMessage,
}

func (m *Request) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Request) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Operation != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintMessage(data, i, uint64(m.Operation))
	}
	if m.Database != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintMessage(data, i, uint64(m.Database))
	}
	if len(m.PeerIPString) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.PeerIPString)))
		i += copy(data[i:], m.PeerIPString)
	}
	if m.ServerIndex != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintMessage(data, i, uint64(m.ServerIndex))
	}
	if len(m.TestName) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.TestName)))
		i += copy(data[i:], m.TestName)
	}
	if len(m.GoogleCloudProjectName) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.GoogleCloudProjectName)))
		i += copy(data[i:], m.GoogleCloudProjectName)
	}
	if len(m.GoogleCloudStorageKey) > 0 {
		data[i] = 0x3a
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.GoogleCloudStorageKey)))
		i += copy(data[i:], m.GoogleCloudStorageKey)
	}
	if len(m.GoogleCloudStorageBucketName) > 0 {
		data[i] = 0x42
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.GoogleCloudStorageBucketName)))
		i += copy(data[i:], m.GoogleCloudStorageBucketName)
	}
	if len(m.GoogleCloudStorageSubDirectory) > 0 {
		data[i] = 0x4a
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.GoogleCloudStorageSubDirectory)))
		i += copy(data[i:], m.GoogleCloudStorageSubDirectory)
	}
	if m.ZookeeperMyID != 0 {
		data[i] = 0x50
		i++
		i = encodeVarintMessage(data, i, uint64(m.ZookeeperMyID))
	}
	if m.ZookeeperMaxClientCnxns != 0 {
		data[i] = 0x58
		i++
		i = encodeVarintMessage(data, i, uint64(m.ZookeeperMaxClientCnxns))
	}
	if m.ZookeeperSnapCount != 0 {
		data[i] = 0x60
		i++
		i = encodeVarintMessage(data, i, uint64(m.ZookeeperSnapCount))
	}
	if len(m.EtcdCompression) > 0 {
		data[i] = 0x6a
		i++
		i = encodeVarintMessage(data, i, uint64(len(m.EtcdCompression)))
		i += copy(data[i:], m.EtcdCompression)
	}
	return i, nil
}

func (m *Response) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Response) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Success {
		data[i] = 0x8
		i++
		if m.Success {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func encodeFixed64Message(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Message(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMessage(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *Request) Size() (n int) {
	var l int
	_ = l
	if m.Operation != 0 {
		n += 1 + sovMessage(uint64(m.Operation))
	}
	if m.Database != 0 {
		n += 1 + sovMessage(uint64(m.Database))
	}
	l = len(m.PeerIPString)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ServerIndex != 0 {
		n += 1 + sovMessage(uint64(m.ServerIndex))
	}
	l = len(m.TestName)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudProjectName)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudStorageKey)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudStorageBucketName)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.GoogleCloudStorageSubDirectory)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ZookeeperMyID != 0 {
		n += 1 + sovMessage(uint64(m.ZookeeperMyID))
	}
	if m.ZookeeperMaxClientCnxns != 0 {
		n += 1 + sovMessage(uint64(m.ZookeeperMaxClientCnxns))
	}
	if m.ZookeeperSnapCount != 0 {
		n += 1 + sovMessage(uint64(m.ZookeeperSnapCount))
	}
	l = len(m.EtcdCompression)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *Response) Size() (n int) {
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func sovMessage(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			m.Operation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Operation |= (Request_Operation(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Database", wireType)
			}
			m.Database = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Database |= (Request_Database(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerIPString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerIPString = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerIndex", wireType)
			}
			m.ServerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ServerIndex |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TestName = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudProjectName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudProjectName = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageKey = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageBucketName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageBucketName = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoogleCloudStorageSubDirectory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoogleCloudStorageSubDirectory = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZookeeperMyID", wireType)
			}
			m.ZookeeperMyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ZookeeperMyID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZookeeperMaxClientCnxns", wireType)
			}
			m.ZookeeperMaxClientCnxns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ZookeeperMaxClientCnxns |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZookeeperSnapCount", wireType)
			}
			m.ZookeeperSnapCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ZookeeperSnapCount |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EtcdCompression", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EtcdCompression = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessage(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("message.proto", fileDescriptorMessage) }

var fileDescriptorMessage = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x6e, 0xda, 0x4e,
	0x14, 0xc5, 0x31, 0x04, 0xb0, 0x2f, 0x21, 0xb1, 0x46, 0xff, 0x7f, 0x33, 0x42, 0x95, 0x85, 0xac,
	0x2c, 0xd8, 0xe0, 0x48, 0x50, 0x45, 0x5d, 0xb4, 0x1b, 0x8c, 0x2a, 0xa1, 0xa8, 0x6d, 0x64, 0x77,
	0xd5, 0xdd, 0x60, 0x6e, 0x5c, 0x1a, 0x98, 0x71, 0x67, 0xc6, 0x11, 0xf4, 0x49, 0xfa, 0x48, 0x59,
	0xf6, 0x11, 0x5a, 0xfa, 0x16, 0x5d, 0x55, 0x0c, 0xc1, 0x09, 0xf9, 0x68, 0x77, 0x73, 0xcf, 0xef,
	0x9c, 0xeb, 0x0f, 0x9d, 0x81, 0xe6, 0x1c, 0x95, 0x62, 0x29, 0x06, 0x99, 0x14, 0x5a, 0x90, 0x2a,
	0x4b, 0x91, 0xeb, 0x56, 0x37, 0x9d, 0xea, 0x4f, 0xf9, 0x38, 0x48, 0xc4, 0xfc, 0x24, 0x15, 0xa9,
	0x38, 0x31, 0x74, 0x9c, 0x5f, 0x98, 0xc9, 0x0c, 0xe6, 0xb4, 0x49, 0xf9, 0xbf, 0xab, 0x50, 0x8f,
	0xf0, 0x4b, 0x8e, 0x4a, 0x93, 0x53, 0x70, 0x44, 0x86, 0x92, 0xe9, 0xa9, 0xe0, 0xd4, 0x6a, 0x5b,
	0x9d, 0x83, 0x1e, 0x0d, 0xcc, 0xd6, 0xe0, 0xc6, 0x12, 0xbc, 0xdf, 0xf2, 0xe8, 0xd6, 0x4a, 0xfa,
	0x60, 0x4f, 0x98, 0x66, 0x63, 0xa6, 0x90, 0x96, 0x4d, 0xec, 0xe8, 0x5e, 0x6c, 0x78, 0x83, 0xa3,
	0xc2, 0x48, 0x7c, 0xd8, 0xcf, 0x10, 0xe5, 0xe8, 0x3c, 0xd6, 0x72, 0xca, 0x53, 0x5a, 0x69, 0x5b,
	0x1d, 0x27, 0xda, 0xd1, 0x48, 0x1b, 0x1a, 0x0a, 0xe5, 0x15, 0xca, 0x11, 0x9f, 0xe0, 0x82, 0xee,
	0xb5, 0xad, 0x4e, 0x33, 0xba, 0x2b, 0x91, 0x16, 0xd8, 0x1a, 0x95, 0x7e, 0xc7, 0xe6, 0x48, 0xab,
	0x66, 0x43, 0x31, 0x93, 0x53, 0x78, 0x96, 0x0a, 0x91, 0xce, 0x30, 0x9c, 0x89, 0x7c, 0x72, 0x2e,
	0xc5, 0x67, 0x4c, 0x36, 0xce, 0x9a, 0x71, 0x3e, 0x41, 0xc9, 0x0b, 0xf8, 0xff, 0x0e, 0x89, 0xb5,
	0x90, 0x2c, 0xc5, 0x33, 0x5c, 0xd2, 0xba, 0x89, 0x3d, 0x0e, 0xc9, 0x00, 0x9e, 0x3f, 0x04, 0x83,
	0x3c, 0xb9, 0xc4, 0xcd, 0x33, 0x6d, 0x13, 0xfe, 0xab, 0x87, 0xbc, 0x01, 0xef, 0x21, 0x8f, 0xf3,
	0xf1, 0x70, 0x2a, 0x31, 0xd1, 0x42, 0x2e, 0xa9, 0x63, 0xb6, 0xfc, 0xc3, 0x45, 0x8e, 0xa1, 0xf9,
	0x55, 0x88, 0x4b, 0xc4, 0x0c, 0xe5, 0xdb, 0xe5, 0x68, 0x48, 0xc1, 0xfc, 0xb9, 0x5d, 0x91, 0xbc,
	0x84, 0xa3, 0x5b, 0x81, 0x2d, 0xc2, 0xd9, 0x14, 0xb9, 0x0e, 0xf9, 0x82, 0x2b, 0xda, 0x68, 0x5b,
	0x9d, 0x4a, 0xf4, 0x14, 0x26, 0x01, 0x90, 0x02, 0xc5, 0x9c, 0x65, 0xa1, 0xc8, 0xb9, 0xa6, 0xfb,
	0x26, 0xf4, 0x08, 0x21, 0x1d, 0x38, 0x44, 0x9d, 0x4c, 0x42, 0x31, 0xcf, 0x24, 0x2a, 0xb5, 0xae,
	0x57, 0xd3, 0x7c, 0xc8, 0x7d, 0xd9, 0xef, 0x82, 0x53, 0x54, 0x8c, 0x38, 0x50, 0x8d, 0x35, 0x93,
	0xda, 0x2d, 0x11, 0x1b, 0xf6, 0x62, 0x2d, 0x32, 0xd7, 0x22, 0x8d, 0x75, 0x5f, 0x95, 0x91, 0xcb,
	0xfe, 0x6b, 0xb0, 0xb7, 0xd5, 0x22, 0x00, 0xb5, 0xf5, 0xb6, 0xab, 0xbe, 0x5b, 0x2a, 0xce, 0x3d,
	0xd7, 0x22, 0x4d, 0x70, 0x3e, 0x0a, 0x71, 0x66, 0x5e, 0xc9, 0x2d, 0xaf, 0x51, 0x28, 0xb8, 0xca,
	0x67, 0x6e, 0xc5, 0x3f, 0x06, 0x3b, 0x42, 0x95, 0x09, 0xae, 0x90, 0x50, 0xa8, 0xab, 0x3c, 0x49,
	0x50, 0x29, 0x53, 0x7d, 0x3b, 0xda, 0x8e, 0xbd, 0x57, 0xd0, 0xf8, 0x20, 0x19, 0x57, 0x99, 0x90,
	0x1a, 0x25, 0xe9, 0x82, 0x6d, 0xc6, 0x0b, 0x94, 0xe4, 0x60, 0xb7, 0xe7, 0xad, 0xc3, 0x62, 0xde,
	0x6c, 0xf5, 0x4b, 0x83, 0xff, 0xae, 0x7f, 0x7a, 0xa5, 0xeb, 0x95, 0x67, 0x7d, 0x5f, 0x79, 0xd6,
	0x8f, 0x95, 0x67, 0x7d, 0xfb, 0xe5, 0x95, 0xc6, 0x35, 0x73, 0xfb, 0xfa, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x3f, 0xff, 0xae, 0x1e, 0xc4, 0x03, 0x00, 0x00,
}
